DLL0(IdacLibVersion, DWORD)
DLL0(IdacType, DWORD)
DLL1(IdacCapabilities, BOOL, TIdacCapability Cap)
DLL1(IdacLock, LPCSTR, LPCSTR UserName)
DLL0(IdacUnlock, void)
DLL0(IdacPowerDown, void)
DLL1(IdacPresent, LONG, LONG Address)
DLL2(IdacBoot, DWORD, LPCSTR FileName, LONG Address)
DLL2(IdacEnableChannel, BOOL, DWORD, BOOL bEnable)
DLL2(IdacScaleRange, BOOL, DWORD Chan, DWORD Index)
DLL2(IdacSetDecimation, BOOL, DWORD Chan, DWORD dwDecimation)
DLL2(IdacSetOffsetAnalogIn, BOOL, DWORD Chan, DWORD Offset)
DLL2(IdacLowPassStrings, void, int *NrOfStrings, const char **ppFilterStrings[])
DLL2(IdacLowPass, BOOL, DWORD Chan, DWORD Index)
DLL2(IdacHighPassStrings, void, int *NrOfStrings, const char **ppFilterStrings[])
DLL2(IdacHighPass, BOOL, DWORD Chan, DWORD Index)
DLL0(IdacGetRanges, LPDWORD)
DLL1(IdacGetStatusFlags, CDD32_STATUS, BOOL bClear)
DLL0(IdacSmpStart, BOOL)
DLL0(IdacSmpStop, BOOL)
DLL1(IdacLockReadBuffer, LPCDD32_SAMPLE, DWORD* pdwCount)
DLL0(IdacUnlockReadBuffer, void)
