DRIVER_EXPORT LONG WINAPI IdacPresent (LONG Address)
DRIVER_EXPORT DWORD WINAPI IdacBoot (LPCSTR FileName, LONG Address)
DRIVER_EXPORT BOOL WINAPI IdacHasBooted()
DRIVER_EXPORT DWORD WINAPI IdacGetDSPFirmwareVersion ()
